// flow-typed signature: c609a704cf996179a94856fa461fc82f
// flow-typed version: <<STUB>>/apollo-test-utils_v^0.2.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-test-utils/dist/src/index' {
  declare module.exports: any;
}

declare module 'apollo-test-utils/dist/src/mocks/mockNetworkInterface' {
  declare module.exports: any;
}

declare module 'apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema' {
  declare module.exports: any;
}

declare module 'apollo-test-utils/dist/src/util/isApolloClient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-test-utils/dist/src/index.js' {
  declare module.exports: $Exports<'apollo-test-utils/dist/src/index'>;
}
declare module 'apollo-test-utils/dist/src/mocks/mockNetworkInterface.js' {
  declare module.exports: $Exports<'apollo-test-utils/dist/src/mocks/mockNetworkInterface'>;
}
declare module 'apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema.js' {
  declare module.exports: $Exports<'apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema'>;
}
declare module 'apollo-test-utils/dist/src/util/isApolloClient.js' {
  declare module.exports: $Exports<'apollo-test-utils/dist/src/util/isApolloClient'>;
}
