// flow-typed signature: 9fa2e59379c95267156d16d82ab8aeb4
// flow-typed version: <<STUB>>/bufferutil_v^3.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bufferutil'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bufferutil' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bufferutil/fallback' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bufferutil/fallback.js' {
  declare module.exports: $Exports<'bufferutil/fallback'>;
}
declare module 'bufferutil/index' {
  declare module.exports: $Exports<'bufferutil'>;
}
declare module 'bufferutil/index.js' {
  declare module.exports: $Exports<'bufferutil'>;
}
