// flow-typed signature: 5dd083f27aaa39652062f3127b1d3d6c
// flow-typed version: <<STUB>>/calendar_v^0.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'calendar/examples/cal' {
  declare module.exports: any;
}

declare module 'calendar/examples/webcal' {
  declare module.exports: any;
}

declare module 'calendar/lib/calendar' {
  declare module.exports: any;
}

declare module 'calendar/test/calendar_tests' {
  declare module.exports: any;
}

declare module 'calendar/test/daylight_time_error' {
  declare module.exports: any;
}

declare module 'calendar/test/jquery' {
  declare module.exports: any;
}

declare module 'calendar/test/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'calendar/examples/cal.js' {
  declare module.exports: $Exports<'calendar/examples/cal'>;
}
declare module 'calendar/examples/webcal.js' {
  declare module.exports: $Exports<'calendar/examples/webcal'>;
}
declare module 'calendar/lib/calendar.js' {
  declare module.exports: $Exports<'calendar/lib/calendar'>;
}
declare module 'calendar/test/calendar_tests.js' {
  declare module.exports: $Exports<'calendar/test/calendar_tests'>;
}
declare module 'calendar/test/daylight_time_error.js' {
  declare module.exports: $Exports<'calendar/test/daylight_time_error'>;
}
declare module 'calendar/test/jquery.js' {
  declare module.exports: $Exports<'calendar/test/jquery'>;
}
declare module 'calendar/test/qunit.js' {
  declare module.exports: $Exports<'calendar/test/qunit'>;
}
