// flow-typed signature: 1466f87718d052585ec0b48244a0a92b
// flow-typed version: <<STUB>>/firepad_v^1.4.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firepad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'firepad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firepad/dist/firepad' {
  declare module.exports: any;
}

declare module 'firepad/dist/firepad.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firepad/dist/firepad.js' {
  declare module.exports: $Exports<'firepad/dist/firepad'>;
}
declare module 'firepad/dist/firepad.min.js' {
  declare module.exports: $Exports<'firepad/dist/firepad.min'>;
}
