// flow-typed signature: 9d0f5c10de8ce4cda7601e03c389f062
// flow-typed version: <<STUB>>/font-awesome-webpack2_v0.0.6/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome-webpack2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome-webpack2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'font-awesome-webpack2/font-awesome-styles.loader' {
  declare module.exports: any;
}

declare module 'font-awesome-webpack2/font-awesome.config' {
  declare module.exports: any;
}

declare module 'font-awesome-webpack2/index.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'font-awesome-webpack2/font-awesome-styles.loader.js' {
  declare module.exports: $Exports<'font-awesome-webpack2/font-awesome-styles.loader'>;
}
declare module 'font-awesome-webpack2/font-awesome.config.js' {
  declare module.exports: $Exports<'font-awesome-webpack2/font-awesome.config'>;
}
declare module 'font-awesome-webpack2/index' {
  declare module.exports: $Exports<'font-awesome-webpack2'>;
}
declare module 'font-awesome-webpack2/index.js' {
  declare module.exports: $Exports<'font-awesome-webpack2'>;
}
declare module 'font-awesome-webpack2/index.loader.js' {
  declare module.exports: $Exports<'font-awesome-webpack2/index.loader'>;
}
