// flow-typed signature: c174ecc4408443b08b823c9a60a35c8d
// flow-typed version: <<STUB>>/graphql-server-express_v^0.6.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-server-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-server-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-server-express/dist/connectApollo' {
  declare module.exports: any;
}

declare module 'graphql-server-express/dist/expressApollo' {
  declare module.exports: any;
}

declare module 'graphql-server-express/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-server-express/dist/connectApollo.js' {
  declare module.exports: $Exports<'graphql-server-express/dist/connectApollo'>;
}
declare module 'graphql-server-express/dist/expressApollo.js' {
  declare module.exports: $Exports<'graphql-server-express/dist/expressApollo'>;
}
declare module 'graphql-server-express/dist/index.js' {
  declare module.exports: $Exports<'graphql-server-express/dist/index'>;
}
