// flow-typed signature: 38c857ca716c3a9b51c46e87d7961031
// flow-typed version: <<STUB>>/postcss-focus_v^1.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-focus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-focus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-focus/index' {
  declare module.exports: $Exports<'postcss-focus'>;
}
declare module 'postcss-focus/index.js' {
  declare module.exports: $Exports<'postcss-focus'>;
}
