// flow-typed signature: 2621aed7829b03efe5528b84527e59d5
// flow-typed version: <<STUB>>/react-app_v^1.1.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app/bin/react-app' {
  declare module.exports: any;
}

declare module 'react-app/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app/bin/react-app.js' {
  declare module.exports: $Exports<'react-app/bin/react-app'>;
}
declare module 'react-app/cli.js' {
  declare module.exports: $Exports<'react-app/cli'>;
}
