// flow-typed signature: 98b4709909a0288a8bb2e850e1a08dd5
// flow-typed version: <<STUB>>/react-file-download_v^0.3.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-file-download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-file-download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-file-download/file-download' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-file-download/file-download.js' {
  declare module.exports: $Exports<'react-file-download/file-download'>;
}
