// flow-typed signature: b6a33b768eaaf986d04ce5c24e0dd4a4
// flow-typed version: <<STUB>>/react-motion-menu_v^0.4.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-motion-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-motion-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-motion-menu/lib/button' {
  declare module.exports: any;
}

declare module 'react-motion-menu/lib/index' {
  declare module.exports: any;
}

declare module 'react-motion-menu/lib/item' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-motion-menu/lib/button.js' {
  declare module.exports: $Exports<'react-motion-menu/lib/button'>;
}
declare module 'react-motion-menu/lib/index.js' {
  declare module.exports: $Exports<'react-motion-menu/lib/index'>;
}
declare module 'react-motion-menu/lib/item.js' {
  declare module.exports: $Exports<'react-motion-menu/lib/item'>;
}
