// flow-typed signature: 2d324ef6a43ea21d779ddb390e2b7fc8
// flow-typed version: <<STUB>>/react-resizable-decorator_v^0.1.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resizable-decorator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resizable-decorator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-resizable-decorator/lib/index' {
  declare module.exports: any;
}

declare module 'react-resizable-decorator/lib/resize-handler' {
  declare module.exports: any;
}

declare module 'react-resizable-decorator/lib/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-resizable-decorator/lib/index.js' {
  declare module.exports: $Exports<'react-resizable-decorator/lib/index'>;
}
declare module 'react-resizable-decorator/lib/resize-handler.js' {
  declare module.exports: $Exports<'react-resizable-decorator/lib/resize-handler'>;
}
declare module 'react-resizable-decorator/lib/styles.js' {
  declare module.exports: $Exports<'react-resizable-decorator/lib/styles'>;
}
