// flow-typed signature: 687cc2c4496a4684044d30efe9f5515e
// flow-typed version: <<STUB>>/react-onscroll_v^1.0.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onscroll/dist/react-onscroll' {
  declare module.exports: any;
}

declare module 'react-onscroll/dist/react-onscroll.min' {
  declare module.exports: any;
}

declare module 'react-onscroll/example/src/example' {
  declare module.exports: any;
}

declare module 'react-onscroll/gulpfile' {
  declare module.exports: any;
}

declare module 'react-onscroll/lib/ScrollEvent' {
  declare module.exports: any;
}

declare module 'react-onscroll/src/ScrollEvent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onscroll/dist/react-onscroll.js' {
  declare module.exports: $Exports<'react-onscroll/dist/react-onscroll'>;
}
declare module 'react-onscroll/dist/react-onscroll.min.js' {
  declare module.exports: $Exports<'react-onscroll/dist/react-onscroll.min'>;
}
declare module 'react-onscroll/example/src/example.js' {
  declare module.exports: $Exports<'react-onscroll/example/src/example'>;
}
declare module 'react-onscroll/gulpfile.js' {
  declare module.exports: $Exports<'react-onscroll/gulpfile'>;
}
declare module 'react-onscroll/lib/ScrollEvent.js' {
  declare module.exports: $Exports<'react-onscroll/lib/ScrollEvent'>;
}
declare module 'react-onscroll/src/ScrollEvent.js' {
  declare module.exports: $Exports<'react-onscroll/src/ScrollEvent'>;
}
