// flow-typed signature: b28c1c31435ed7c32128eea5cee90e9d
// flow-typed version: <<STUB>>/react-rnd_v^4.2.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rnd/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rnd/lib/index.js' {
  declare module.exports: $Exports<'react-rnd/lib/index'>;
}
