// flow-typed signature: 5a48772788d89c62fbf107a5aa93179c
// flow-typed version: <<STUB>>/react-redux-firebase_v^1.3.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-firebase/dist/react-redux-firebase' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/dist/react-redux-firebase.min' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/compose' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/connect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/constants' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/helpers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/events' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/populate' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/compose' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/connect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/constants' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/events' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/populate' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/compose' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/connect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/constants' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/helpers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/events' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/populate' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-firebase/dist/react-redux-firebase.js' {
  declare module.exports: $Exports<'react-redux-firebase/dist/react-redux-firebase'>;
}
declare module 'react-redux-firebase/dist/react-redux-firebase.min.js' {
  declare module.exports: $Exports<'react-redux-firebase/dist/react-redux-firebase.min'>;
}
declare module 'react-redux-firebase/es/actions/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/auth'>;
}
declare module 'react-redux-firebase/es/actions/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/index'>;
}
declare module 'react-redux-firebase/es/actions/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/query'>;
}
declare module 'react-redux-firebase/es/actions/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/storage'>;
}
declare module 'react-redux-firebase/es/compose.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/compose'>;
}
declare module 'react-redux-firebase/es/connect.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/connect'>;
}
declare module 'react-redux-firebase/es/constants.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/constants'>;
}
declare module 'react-redux-firebase/es/helpers.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/helpers'>;
}
declare module 'react-redux-firebase/es/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/index'>;
}
declare module 'react-redux-firebase/es/reducer.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/reducer'>;
}
declare module 'react-redux-firebase/es/utils/actions.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/actions'>;
}
declare module 'react-redux-firebase/es/utils/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/auth'>;
}
declare module 'react-redux-firebase/es/utils/events.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/events'>;
}
declare module 'react-redux-firebase/es/utils/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/index'>;
}
declare module 'react-redux-firebase/es/utils/populate.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/populate'>;
}
declare module 'react-redux-firebase/es/utils/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/query'>;
}
declare module 'react-redux-firebase/es/utils/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/storage'>;
}
declare module 'react-redux-firebase/lib/actions/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/auth'>;
}
declare module 'react-redux-firebase/lib/actions/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/index'>;
}
declare module 'react-redux-firebase/lib/actions/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/query'>;
}
declare module 'react-redux-firebase/lib/actions/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/storage'>;
}
declare module 'react-redux-firebase/lib/compose.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/compose'>;
}
declare module 'react-redux-firebase/lib/connect.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/connect'>;
}
declare module 'react-redux-firebase/lib/constants.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/constants'>;
}
declare module 'react-redux-firebase/lib/helpers.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/helpers'>;
}
declare module 'react-redux-firebase/lib/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/index'>;
}
declare module 'react-redux-firebase/lib/reducer.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/reducer'>;
}
declare module 'react-redux-firebase/lib/utils/actions.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/actions'>;
}
declare module 'react-redux-firebase/lib/utils/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/auth'>;
}
declare module 'react-redux-firebase/lib/utils/events.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/events'>;
}
declare module 'react-redux-firebase/lib/utils/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/index'>;
}
declare module 'react-redux-firebase/lib/utils/populate.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/populate'>;
}
declare module 'react-redux-firebase/lib/utils/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/query'>;
}
declare module 'react-redux-firebase/lib/utils/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/storage'>;
}
declare module 'react-redux-firebase/src/actions/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/auth'>;
}
declare module 'react-redux-firebase/src/actions/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/index'>;
}
declare module 'react-redux-firebase/src/actions/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/query'>;
}
declare module 'react-redux-firebase/src/actions/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/storage'>;
}
declare module 'react-redux-firebase/src/compose.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/compose'>;
}
declare module 'react-redux-firebase/src/connect.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/connect'>;
}
declare module 'react-redux-firebase/src/constants.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/constants'>;
}
declare module 'react-redux-firebase/src/helpers.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/helpers'>;
}
declare module 'react-redux-firebase/src/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/index'>;
}
declare module 'react-redux-firebase/src/reducer.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/reducer'>;
}
declare module 'react-redux-firebase/src/utils/actions.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/actions'>;
}
declare module 'react-redux-firebase/src/utils/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/auth'>;
}
declare module 'react-redux-firebase/src/utils/events.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/events'>;
}
declare module 'react-redux-firebase/src/utils/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/index'>;
}
declare module 'react-redux-firebase/src/utils/populate.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/populate'>;
}
declare module 'react-redux-firebase/src/utils/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/query'>;
}
declare module 'react-redux-firebase/src/utils/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/storage'>;
}
