// flow-typed signature: 868524741b2342f9a8b1a417c80e3400
// flow-typed version: <<STUB>>/redux-slider-monitor_v^1.0.7/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-slider-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-slider-monitor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-slider-monitor/lib/reducers' {
  declare module.exports: any;
}

declare module 'redux-slider-monitor/lib/Slider' {
  declare module.exports: any;
}

declare module 'redux-slider-monitor/lib/SliderButton' {
  declare module.exports: any;
}

declare module 'redux-slider-monitor/lib/SliderMonitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-slider-monitor/lib/reducers.js' {
  declare module.exports: $Exports<'redux-slider-monitor/lib/reducers'>;
}
declare module 'redux-slider-monitor/lib/Slider.js' {
  declare module.exports: $Exports<'redux-slider-monitor/lib/Slider'>;
}
declare module 'redux-slider-monitor/lib/SliderButton.js' {
  declare module.exports: $Exports<'redux-slider-monitor/lib/SliderButton'>;
}
declare module 'redux-slider-monitor/lib/SliderMonitor.js' {
  declare module.exports: $Exports<'redux-slider-monitor/lib/SliderMonitor'>;
}
