// flow-typed signature: 472c739b4296f0d185f39406023c926e
// flow-typed version: <<STUB>>/redux-socket.io_v^1.3.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-socket.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-socket.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-socket.io/dist/index' {
  declare module.exports: any;
}

declare module 'redux-socket.io/gulpfile' {
  declare module.exports: any;
}

declare module 'redux-socket.io/src/index' {
  declare module.exports: any;
}

declare module 'redux-socket.io/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-socket.io/dist/index.js' {
  declare module.exports: $Exports<'redux-socket.io/dist/index'>;
}
declare module 'redux-socket.io/gulpfile.js' {
  declare module.exports: $Exports<'redux-socket.io/gulpfile'>;
}
declare module 'redux-socket.io/src/index.js' {
  declare module.exports: $Exports<'redux-socket.io/src/index'>;
}
declare module 'redux-socket.io/test/index.js' {
  declare module.exports: $Exports<'redux-socket.io/test/index'>;
}
