// flow-typed signature: b42cb8d441b24dbcc7aae223fc3d0f41
// flow-typed version: <<STUB>>/smooth-scroll_vgithub:cferdinandi/smooth-scroll/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smooth-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'smooth-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smooth-scroll/dist/js/smooth-scroll' {
  declare module.exports: any;
}

declare module 'smooth-scroll/dist/js/smooth-scroll.min' {
  declare module.exports: any;
}

declare module 'smooth-scroll/docs/dist/js/smooth-scroll' {
  declare module.exports: any;
}

declare module 'smooth-scroll/docs/dist/js/smooth-scroll.min' {
  declare module.exports: any;
}

declare module 'smooth-scroll/gulpfile' {
  declare module.exports: any;
}

declare module 'smooth-scroll/src/js/smooth-scroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smooth-scroll/dist/js/smooth-scroll.js' {
  declare module.exports: $Exports<'smooth-scroll/dist/js/smooth-scroll'>;
}
declare module 'smooth-scroll/dist/js/smooth-scroll.min.js' {
  declare module.exports: $Exports<'smooth-scroll/dist/js/smooth-scroll.min'>;
}
declare module 'smooth-scroll/docs/dist/js/smooth-scroll.js' {
  declare module.exports: $Exports<'smooth-scroll/docs/dist/js/smooth-scroll'>;
}
declare module 'smooth-scroll/docs/dist/js/smooth-scroll.min.js' {
  declare module.exports: $Exports<'smooth-scroll/docs/dist/js/smooth-scroll.min'>;
}
declare module 'smooth-scroll/gulpfile.js' {
  declare module.exports: $Exports<'smooth-scroll/gulpfile'>;
}
declare module 'smooth-scroll/src/js/smooth-scroll.js' {
  declare module.exports: $Exports<'smooth-scroll/src/js/smooth-scroll'>;
}
