// flow-typed signature: dbc939c6139f323d39c8def347422f9a
// flow-typed version: <<STUB>>/smoothy_v^1.1.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smoothy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'smoothy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smoothy/dist/smoothy.min' {
  declare module.exports: any;
}

declare module 'smoothy/gulpfile' {
  declare module.exports: any;
}

declare module 'smoothy/src/smoothy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smoothy/dist/smoothy.min.js' {
  declare module.exports: $Exports<'smoothy/dist/smoothy.min'>;
}
declare module 'smoothy/gulpfile.js' {
  declare module.exports: $Exports<'smoothy/gulpfile'>;
}
declare module 'smoothy/src/smoothy.js' {
  declare module.exports: $Exports<'smoothy/src/smoothy'>;
}
