// flow-typed signature: 925407ec1ad30120384472885c397f1c
// flow-typed version: <<STUB>>/socket.io-react_v^1.1.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io-react/build/index' {
  declare module.exports: any;
}

declare module 'socket.io-react/build/socket-connect' {
  declare module.exports: any;
}

declare module 'socket.io-react/build/SocketProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io-react/build/index.js' {
  declare module.exports: $Exports<'socket.io-react/build/index'>;
}
declare module 'socket.io-react/build/socket-connect.js' {
  declare module.exports: $Exports<'socket.io-react/build/socket-connect'>;
}
declare module 'socket.io-react/build/SocketProvider.js' {
  declare module.exports: $Exports<'socket.io-react/build/SocketProvider'>;
}
