// flow-typed signature: a61f3ea74f594288d95721568e7d43bd
// flow-typed version: <<STUB>>/sweet-scroll_v^2.2.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sweet-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sweet-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sweet-scroll/src/dom' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/easings' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/elements' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/events' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/math' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/request-animation-frame' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/scroll-tween' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/selectors' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/supports' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/sweet-scroll' {
  declare module.exports: any;
}

declare module 'sweet-scroll/src/utils' {
  declare module.exports: any;
}

declare module 'sweet-scroll/sweet-scroll' {
  declare module.exports: any;
}

declare module 'sweet-scroll/sweet-scroll.min' {
  declare module.exports: any;
}

declare module 'sweet-scroll/test/sweet-scroll.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sweet-scroll/src/dom.js' {
  declare module.exports: $Exports<'sweet-scroll/src/dom'>;
}
declare module 'sweet-scroll/src/easings.js' {
  declare module.exports: $Exports<'sweet-scroll/src/easings'>;
}
declare module 'sweet-scroll/src/elements.js' {
  declare module.exports: $Exports<'sweet-scroll/src/elements'>;
}
declare module 'sweet-scroll/src/events.js' {
  declare module.exports: $Exports<'sweet-scroll/src/events'>;
}
declare module 'sweet-scroll/src/math.js' {
  declare module.exports: $Exports<'sweet-scroll/src/math'>;
}
declare module 'sweet-scroll/src/request-animation-frame.js' {
  declare module.exports: $Exports<'sweet-scroll/src/request-animation-frame'>;
}
declare module 'sweet-scroll/src/scroll-tween.js' {
  declare module.exports: $Exports<'sweet-scroll/src/scroll-tween'>;
}
declare module 'sweet-scroll/src/selectors.js' {
  declare module.exports: $Exports<'sweet-scroll/src/selectors'>;
}
declare module 'sweet-scroll/src/supports.js' {
  declare module.exports: $Exports<'sweet-scroll/src/supports'>;
}
declare module 'sweet-scroll/src/sweet-scroll.js' {
  declare module.exports: $Exports<'sweet-scroll/src/sweet-scroll'>;
}
declare module 'sweet-scroll/src/utils.js' {
  declare module.exports: $Exports<'sweet-scroll/src/utils'>;
}
declare module 'sweet-scroll/sweet-scroll.js' {
  declare module.exports: $Exports<'sweet-scroll/sweet-scroll'>;
}
declare module 'sweet-scroll/sweet-scroll.min.js' {
  declare module.exports: $Exports<'sweet-scroll/sweet-scroll.min'>;
}
declare module 'sweet-scroll/test/sweet-scroll.spec.js' {
  declare module.exports: $Exports<'sweet-scroll/test/sweet-scroll.spec'>;
}
