// flow-typed signature: 68c860ccbe8df886740aa04bcd105397
// flow-typed version: <<STUB>>/tls_v^0.0.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tls/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tls/index' {
  declare module.exports: $Exports<'tls'>;
}
declare module 'tls/index.js' {
  declare module.exports: $Exports<'tls'>;
}
declare module 'tls/test/index.js' {
  declare module.exports: $Exports<'tls/test/index'>;
}
