// flow-typed signature: b33f6298419531543f4246e085b88759
// flow-typed version: <<STUB>>/utf-8-validate_v^3.0.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utf-8-validate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'utf-8-validate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utf-8-validate/fallback' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utf-8-validate/fallback.js' {
  declare module.exports: $Exports<'utf-8-validate/fallback'>;
}
declare module 'utf-8-validate/index' {
  declare module.exports: $Exports<'utf-8-validate'>;
}
declare module 'utf-8-validate/index.js' {
  declare module.exports: $Exports<'utf-8-validate'>;
}
