export const NOTE_WRITE = "NOTE_WRITE"

// TO-DO LIST ACTIONS
export const TODO_ADD = "TODO_ADD";
export const TODO_CHANGE_STATUS = "TODO_CHANGE_STATUS";
export const TODO_REMOVE = "TODO_REMOVE";

// NOTE ACTIONS
export const NOTE_ONCHANGE = "NOTE_ONCHANGE"

// CALENDAR ACTIONS

export const CALENDAR_GET_DATA = "CALENDAR_GET_DATA"
export const CALENDAR_REQUEST_DATA = "CALENDAR_REQUEST_DATA"
export const CALENDAR_FAIL_DATA = "CALENDAR_FAIL_DATA"

export const CALENDAR_POST_SEND = "CALENDAR_POST_SEND"
export const CALENDAR_POST_SUCCESS = "CALENDAR_POST_SUCCESS"
export const CALENDAR_POST_FAIL = "CALENDAR_POST_FAIL"
