
export const NOTE_WRITE = "NOTE_WRITE"

// TO-DO LIST ACTIONS
export const TODO_ADD = "TODO_ADD";
export const TODO_CHANGE_STATUS = "TODO_CHANGE_STATUS";
export const TODO_REMOVE = "TODO_REMOVE";

// NOTE ACTIONS
export const NOTE_ONCHANGE = "NOTE_ONCHANGE"

// CALENDAR ACTIONS

export const CALENDAR_GET_DATA = "CALENDAR_GET_DATA"
export const CALENDAR_REQUEST_DATA = "CALENDAR_REQUEST_DATA"
export const CALENDAR_FAIL_DATA = "CALENDAR_FAIL_DATA"

export const CALENDAR_POST_SEND = "CALENDAR_POST_SEND"
export const CALENDAR_POST_SUCCESS = "CALENDAR_POST_SUCCESS"
export const CALENDAR_POST_FAIL = "CALENDAR_POST_FAIL"


// CHAT ACTIONS
export const CHAT_CHANGE_NAME = "CHAT_CHANGE_NAME";
export const CHAT_NEW_MESSAGE = "CHAT_NEW_MESSAGE";
export const CHAT_USER_JOIN = "CHAT_USER_JOIN";
export const CHAT_NEW_USER = "CHAT_NEW_USER";
export const CHAT_USER_LEFT = "CHAT_USER_LEFT";
export const CHAT_REQUEST_CHANGE = "CHAT_REQUEST_CHANGE";