
export const NOTE_WRITE = "NOTE_WRITE"

// USER ACTIONS
export const USER_REQUEST_CHECK_AUTH = "USER_REQUEST_CHECK_AUTH";
export const USER_REQUEST_LOG_IN = "USER_REQUEST_LOG_IN";
export const USER_SUCCESS_LOG_IN = "USER_SUCCESS_LOG_IN";
export const USER_FAIL_LOG_IN = "USER_FAIL_LOG_IN";
export const USER_REQUEST_SIGN_UP = "USER_REQUEST_SIGN_UP";
export const USER_SUCCESS_SIGN_UP = "USER_SUCCESS_SIGN_UP";
export const USER_FAIL_SIGN_UP = "USER_FAIL_SIGN_UP";
export const USER_LOG_OUT = "USER_LOG_OUT";

// PROJECT ACTIONS

export const PROJECT_REQUEST_GET  = "PROJECT_REQUEST_GET"; 
export const PROJECT_SUCCESS_GET  = "PROJECT_SUCCESS_GET"; 
export const PROJECT_FAIL_GET = "PROJECT_FAIL_GET";
export const PROJECT_REQUEST_POST  = "PROJECT_REQUEST_POST"; 
export const PROJECT_SUCCESS_POST  = "PROJECT_SUCCESS_POST"; 
export const PROJECT_FAIL_POST = "PROJECT_FAIL_POST";
export const PROJECT_REQUEST_DELETE  = "PROJECT_REQUEST_DELETE"; 
export const PROJECT_SUCCESS_DELETE  = "PROJECT_SUCCESS_DELETE"; 
export const PROJECT_FAIL_DELETE = "PROJECT_FAIL_DELETE";

// TO-DO LIST ACTIONS
export const TODO_ADD = "TODO_ADD";
export const TODO_CHANGE_STATUS = "TODO_CHANGE_STATUS";
export const TODO_REMOVE = "TODO_REMOVE";

// NOTE ACTIONS
export const NOTE_ONCHANGE = "NOTE_ONCHANGE";

// CALENDAR ACTIONS
export const CALENDAR_GET_DATA = "CALENDAR_GET_DATA";
export const CALENDAR_REQUEST_DATA = "CALENDAR_REQUEST_DATA";
export const CALENDAR_FAIL_DATA = "CALENDAR_FAIL_DATA";

export const CALENDAR_POST_SEND = "CALENDAR_POST_SEND";
export const CALENDAR_POST_SUCCESS = "CALENDAR_POST_SUCCESS";
export const CALENDAR_POST_FAIL = "CALENDAR_POST_FAIL";

export const CALENDAR_CHANGE_MONTH = "CALENDAR_CHANGE_MONTH";
export const CALENDAR_CHANGE_WEEK = "CALENDAR_CHANGE_WEEK";

export const CALENDAR_SELECT_DATE = "CALENDAR_SELECT_DATE";

export const CALENDAR_TOGGLE = "CALENDAR_TOGGLE";

// CHAT ACTIONS
export const CHAT_CHANGE_NAME = "CHAT_CHANGE_NAME";
export const CHAT_NEW_MESSAGE = "CHAT_NEW_MESSAGE";
export const CHAT_USER_JOIN = "CHAT_USER_JOIN";
export const CHAT_NEW_USER = "CHAT_NEW_USER";
export const CHAT_USER_LEFT = "CHAT_USER_LEFT";
export const CHAT_REQUEST_DATA = "CHAT_REQUEST_DATA";
export const CHAT_RECEIVE_DATA = "CHAT_RECEIVE_DATA";
export const CHAT_FAIL_DATA = "CHAT_FAIL_DATA";
export const CHAT_POSTSEND_DATA = "CHAT_POSTSEND_DATA";
export const CHAT_POSTSUCCESS_DATA = "CHAT_POSTSUCCESS_DATA";
export const CHAT_POSTFAIL_DATA = "CHAT_POSTFAIL_DATA";


/* WhiteBoard - Start */
export const CHANGE_CONTENT_STATE = "CHANGE_CONTENT_STATE"; // will be deprecated
export const CHANGE_EDITOR_STATE = "CHANGE_EDITOR_STATE";
export const ADD_EDITOR_STATE = "ADD_EDITOR_STATE";
/* WhiteBoard - End */

// FILE ACTIONS
export const ADD_FILE = "ADD_FILE"
export const DELETE_FILE = "DELETE_FILE";
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const EDIT_FILE = "EDIT_FILE";
